function Students(name,email,age,){
    this.name;
    this.email;
    this.age;
}


var studentDetails = [
    new Students("dua","dua@gmail.com",19),
    new Students("nida","nida@gmail.com",19),
    new Students("maham","maham@gmail.com",20),
    new Students("aqsa","aqsa@gmail.com",19),
    new Students("zunaira","zunaira@gmail.com",19),
    new Students("tehreem","tehreem@gmail.com",20),
    new Students("rida","rida@gmail.com",20),
    new Students("umaima","umaima@gmail.com",19),
    new Students("sobia","sobia@gmail.com",21),
    new Students("neha","neha@gmail.com",19),
    new Students("ishrat","ishrat@gmail.com",23),
    new Students("inza","inza@gmail.com",19),
    new Students("zobia","zobia@gmail.com",25),
    new Students("bisma","bisma@gmail.com",23),
    new Students("laraib","laraib@gmail.com",22),
    new Students("shaheen","shaheen@gmail.com",38),
    new Students("maqboola","maqboola@gmail.com",32),
    new Students("feeha","feeha@gmail.com",39),
    new Students("javeria","javeria@gmail.com",12),
    new Students("mehwish","mehwish@gmail.com",36),
    new Students("kulsoom","kulsoom@gmail.com",42),
    new Students("tania","tania@gmail.com",24),
    new Students("misbah","misbah@gmail.com",20),
    new Students("maryam","maryam@gmail.com",21),
    new Students("sadaf","sadaf@gmail.com",29),
    new Students("faiza","fiza@gmail.com",20),
    new Students("ayesha","ayesha@gmail.com",24),
    new Students("zoha","zoha@gmail.com",19),
    new Students("saba","saba@gmail.com",22),
    new Students("muqaddas","muqaddas@gmail.com",29),
    new Students("sonia","sonia@gmail.com",23),
    new Students("riffat","riffat@gmail.com",25),
    new Students("unzila","unzila@gmail.com",24),
    new Students("meerab","meerab@gmail.com",22),
    new Students("laiba","laiba@gmail.com",25),
    new Students("sana","sana@gmail.com",27),
    new Students("fariya","fariya@gmail.com",29),
    new Students("sumera","sumera@gmail.com",33),
    new Students("fiza","fiza@gmail.com",39),
    new Students("amna","amna@gmail.com",40),
    new Students("muskan","muskan@gmail.com",22),
    new Students("kashish","kashish@gmail.com",26),
    new Students("alisha","alisha@gmail.com",29),
    new Students("atiya","atiya@gmail.com",23),
    new Students("anshara","anshara@gmail.com",20),
    new Students("isha","isha@gmail.com",20),
    new Students("shabana","shabana@gmail.com",21),
    new Students("sadia","sadia@gmail.com",22),
    new Students("nabeela","nabeela@gmail.com",25),
    new Students("neelam","neelam@gmail.com",23),
]
console.log(studentDetails);